
import { Contract, PlanningItem } from '../types';

export const MOCK_CONTRACTS: Contract[] = [
    {
        id: '1',
        item: 'Ноутбук Lenovo ThinkPad',
        dk_code: '30210000-4',
        kekv: '3110',
        quantity: 10,
        unit: 'шт.',
        expected_cost: 350000,
        contract_number: '123-A',
        contract_date: '2023-05-15',
        year: 2023,
        legal_date: '2023-05-20',
        financial_date: '2023-05-25',
        contracting_party: 'ТОВ "ТехноСвіт"',
        du: false,
        reporting: true,
        procurement_type: 'Прямий',
        prozorro_link: 'http://prozorro.gov.ua/1',
        contract_file_name: 'contract1.pdf',
        announced_winner: '2023-05-10',
        contract_file_path: '/contracts/contract1.pdf',
    },
    {
        id: '2',
        item: 'Папір офісний А4',
        dk_code: '30197630-1',
        kekv: '2210',
        quantity: 500,
        unit: 'пачка',
        expected_cost: 75000,
        contract_number: '234-B',
        contract_date: '2023-06-01',
        year: 2023,
        legal_date: '2023-06-05',
        financial_date: '2023-06-10',
        contracting_party: 'ПП "ПапірПром"',
        du: true,
        reporting: true,
        procurement_type: 'Процедура',
        prozorro_link: 'http://prozorro.gov.ua/2',
        contract_file_name: 'contract2.pdf',
        announced_winner: '2023-05-25',
        contract_file_path: '/contracts/contract2.pdf',
    },
    {
        id: '3',
        item: 'Ремонт офісних приміщень',
        dk_code: '45453000-7',
        kekv: '2240',
        quantity: 1,
        unit: 'послуга',
        expected_cost: 1200000,
        contract_number: '456-C',
        contract_date: '2024-01-20',
        year: 2024,
        legal_date: '2024-01-22',
        financial_date: '2024-02-01',
        contracting_party: 'ТОВ "БудМайстер"',
        du: false,
        reporting: false,
        procurement_type: 'Процедура',
        prozorro_link: 'http://prozorro.gov.ua/3',
        contract_file_name: 'contract3.pdf',
        announced_winner: '2024-01-15',
        contract_file_path: '/contracts/contract3.pdf',
    },
    {
        id: '4',
        item: 'Канцелярські товари',
        dk_code: '30192000-1',
        kekv: '2210',
        quantity: 1,
        unit: 'комплект',
        expected_cost: 25000,
        contract_number: '789-D',
        contract_date: '2024-02-10',
        year: 2024,
        legal_date: '2024-02-12',
        financial_date: '2024-02-15',
        contracting_party: 'ФОП "Петренко"',
        du: false,
        reporting: true,
        procurement_type: 'Прямий',
        prozorro_link: '',
        contract_file_name: 'contract4.pdf',
        announced_winner: '2024-02-05',
        contract_file_path: '/contracts/contract4.pdf',
    }
];

export const MOCK_PLANNING_ITEMS: PlanningItem[] = [
    {
        id: 'p1',
        name: 'Закупівля комп\'ютерної техніки',
        classifiers: '30210000-4',
        kekv: '3110',
        budget: '500,000 грн',
        procedure: 'Відкриті торги',
        start_date: '2024-09-01',
        volume: '20 ноутбуків',
        notes: 'Для нового відділу'
    },
    {
        id: 'p2',
        name: 'Послуги з прибирання',
        classifiers: '90910000-9',
        kekv: '2240',
        budget: '200,000 грн',
        procedure: 'Спрощена закупівля',
        start_date: '2025-01-01',
        volume: '12 місяців',
        notes: 'Щоденне прибирання'
    }
];
